### ISSUE TITLE
Error: Algorithm native:polygonize not found - Qgis minimum version for mappy?

### ISSUE THREAD

**Issue by afrigeri** [planmap-eu/mappy#3]
Looks like mappy is not finding a function:  "Error: Algorithm native:polygonize not found".

![image](https://user-images.githubusercontent.com/158104/106579547-1e443c00-6541-11eb-952a-e5624b489612.png)

QGIS version: 3.10.9-A Coruña
Qt version: 5.14.2
GDAL version: 3.1.3
GEOS version: 3.8.1-CAPI-1.13.3
PROJ version: Rel. 7.1.0, August 1st, 2020

On QGIS 3.16 it works ok, maybe mappy needs a minimum version of QGIS?

**Comment by luca-penasa** [comment]
Thanks ale, latest release should now work also on older versions.
